# Copyright 2024-2026 The Khronos Group Inc.
# SPDX-License-Identifier: Apache-2.0

# Gitlab CI file for Sample-Docs spec generation

# All stages use the same Docker image, so there are no prerequisites
# We now refer to the container by its SHA instead of the name, to prevent
# caching problems when updating the image.
# image: khronosgroup/docker-images:asciidoctor-spec
image: khronosgroup/docker-images@sha256:f1ca671f3bdb10ad49e238b9bf28853088a21af49504498fc9084c9b4fea4762

# Verify repository license compliance
license-check:
  stage: build
  before_script:
    # Nothing, all prerequisites are in the Docker image
  script:
    - reuse lint
  allow_failure: false

# Build the specification and generate any associated files
spec-generate:
  stage: build
  before_script:
    # Nothing, all prerequisites are in the Docker image
  script:
    - make html pdf
  artifacts:
    when: always
    paths:
      - gen/
    expire_in: 1 week
