// Copyright 2024 The Khronos Group Inc.
// SPDX-License-Identifier: CC-BY-4.0

= COPYING file for the KhronosGroup/Sample-Repo project

[NOTE]
.Note
====
COPYING describes the full range of licenses used in a repository,
and how they are applied.
Ideally, only the standard Khronos licenses, CC-BY-4.0 for documents and
Apache 2.0 for everything else, will be used.
In the event you incorporate external dependencies under other licenses,
make sure to describe them briefly below.
====

== Licenses

The Sample-Repo project uses several licenses.

* The source files (in asciidoc and other formats) for the Vulkan
  Specification, reference pages, and supporting documentation are licensed
  under the Creative Commons Attribution 4.0 International License (SPDX
  license identifier "`CC-BY-4.0`").
* Header files, scripts, programs, XML files, and other tooling used or
  generated as part of the build process are typically licensed under the
  Apache License, Version 2.0 (SPDX license identifier "`Apache-2.0`").
* For compatibility with external developers working in GPLed projects who
  have requested it, some specific files are licensed under a dual (SPDX
  license identifier "`Apache-2.0 OR MIT`" License).
* There are a few remaining files adopted from other open source projects,
  such as the `optimize-pdf` script and a copy of the KaTeX distribution
  files. Such files continue under their original MIT licenses.
  We have not added SPDX license identifiers to such externally originated
  files. Instead, they are tagged in the `.reuse/dep5` file.

Users outside Khronos who create and post specifications from this
repository, whether modified or not, should use the CC-BY-4.0 license on the
*output* documents (HTML, PDF, etc.) they generate.
This is the default when building the Specification.


== Frequently Asked Questions

Q: Why are the HTML and PDF Specifications posted on Khronos' website under
a license which is neither CC-BY-4.0 nor Apache-2.0?

A: The Specifications posted by Khronos are licensed under the proprietary
Khronos Specification License.
Only these Specifications are Ratified by the Khronos Board of Promoters,
and therefore they are the only Specifications covered by the Khronos
Intellectual Property Rights Policy.

[NOTE]
.Note
====
There is no IP, as such, in the Sample-Repo specification; it is
simply documentation.
However, all Khronos repositories for actual Specifications will need to be
ratified, so this comment is retained as boilerplate.
====


Q: Does Khronos allow the creation and distribution of modified versions of
the Sample Repository Specification, such as translations to other
languages?

A: Yes. Such modified Specifications, since they are not created by Khronos,
should be placed under the CC-BY-4.0 license.
If you believe your modifications are of general interest, consider
contributing them back by making a pull request on the Sample-Repo project.


Q: Can I contribute changes to the Sample Repository Specification?

A: Yes, by opening an Issue or Pull Request (PR) on the
link:https://github.com/KhronosGroup/Sample-Repo/[Sample-Repo]
Github project.
You must execute a click-through Contributor License Agreement, which brings
your changes under the umbrella of the Khronos IP policy.


Q: Can you change the license on your files so they're compatible with my
license?

A: We use a dual CC-BY-4.0 / MIT license on certain files when that is
essential to make them compatible with GPL-licensed projects.

If you *require* GPL compatibility for use of other Apache-2.0 licensed
files in our repository, please raise an issue identifying the files and we
will consider changing those specific files to the dual license as well.

