// Copyright 2024 The Khronos Group Inc.
// SPDX-License-Identifier: CC-BY-4.0

= COPYING file for the KhronosGroup/Sample-Docs project

[NOTE]
.Note
====
COPYING describes the full range of licenses used in a repository,
and how they are applied.
Ideally, only the standard Khronos licenses, CC-BY-4.0 for documents and
Apache 2.0 for everything else, will be used.
In the event you incorporate external dependencies under other licenses,
make sure to describe them briefly below.
====

== Licenses

The Sample-Docs project uses several licenses.

* The source files (in asciidoc and other formats) for the Sample
  Specification and supporting documentation are licensed under the Creative
  Commons Attribution 4.0 International License (SPDX license identifier
  "`CC-BY-4.0`").
* Header files, scripts, programs, XML files, and other tooling used or
  generated as part of the build process are typically licensed under the
  Apache License, Version 2.0 (SPDX license identifier "`Apache-2.0`").
* There are a few files adopted from other open source projects, such as
  `config/khronos.css` script and a copy of the KaTeX distribution files.
  Such files continue under their original MIT licenses.
  We have not added SPDX license identifiers to such externally originated
  files.
  Instead, they are tagged in the `.reuse/dep5` file.
* For compatibility with external developers working in LGPLed projects who
  have requested it, some specific files can be licensed under a dual (SPDX
  license identifier "`Apache-2.0 OR MIT`") License.
  No such files are in this repository at present.

Users outside Khronos who create and post specifications from this
repository, whether modified or not, should use the CC-BY-4.0 license on the
*output* documents (HTML, PDF, etc.) they generate.
This is the default when building the Sample Specification.


== Frequently Asked Questions

Q: Why are HTML and PDF specifications posted on Khronos' website under a
license which is neither CC-BY-4.0 nor Apache-2.0?

A: The Specifications posted by Khronos are licensed under the proprietary
Khronos Specification Copyright License.
Only these Specifications are Ratified by the Khronos Board of Promoters,
and therefore they are the only Specifications covered by the Khronos
Intellectual Property Rights Policy.

[NOTE]
.Note
====
There is no IP in the Sample-Docs specification. It is simply documentation
and is published under CC-BY-4.0.

However, all actual Khronos specification will need to be ratified and
published under the Khronos Specification Copyright License, so this
question is included in the Sample Specification.
====


Q: Does Khronos allow the creation and distribution of modified versions of
the Sample Specification, such as translations to other languages?

A: Yes. Such modified specifications, since they are not created by Khronos,
should be placed under the CC-BY-4.0 license.
If you believe your modifications are of general interest, consider
contributing them back by making a pull request on the Sample-Docs project.


Q: Can I request or contribute changes to the Sample Specification?

A: Yes, by opening an Issue or Pull Request (PR) on the
link:https://github.com/KhronosGroup/Sample-Docs/[Sample-Docs]
Github project.
PRs must execute a click-through Contributor License Agreement, which brings
your changes under the umbrella of the Khronos IP policy.


Q: Can you change the license on your files so they're compatible with my
license?

A: We use a dual Apache 2.0 / MIT license on certain files when that is
essential to make them compatible with LGPL-licensed projects.

If you *require* LGPL compatibility for use of other Apache-2.0 licensed
files in our repository, please raise an issue identifying the files and we
will consider changing those specific files to the dual license as well.

