// Copyright 2024 The Khronos Group Inc.
// SPDX-License-Identifier: CC-BY-4.0

= LICENSE File for the KhronosGroup/Sample-Docs Project

[NOTE]
.Note
====
The most common GitHub conventions is for the LICENSE file to contain a
single license that applies to an entire repository.

This is not practical for Khronos specification repositories, which will
always contain files under a mix of at least three licenses, and sometimes
many more than three.

Our convention is that LICENSE must enumerate all licenses used in a Khronos
specification repository.
This file does not go into detail; that is the purpose of the COPYING file
and the LICENSES directory.
====

Files in this repository fall under one of these licenses:

  * SPDX license identifier: "`Apache-2.0 OR MIT`"
  ** Apache License 2.0 OR MIT License
  ** For files which need to be usable in GPL-licensed projects.

  * SPDX license identifier: "`Apache-2.0`"
  ** Apache License 2.0
  ** For code, scripts, and tooling.

  * SPDX license identifier: "`CC-BY-4.0`"
  ** Creative Commons Attribution 4.0 International
  ** For specification source documents

  * SPDX license identifier: "`MIT`"
  ** MIT License
  ** For files copied from other MIT-licensed projects

Full license text of these licenses is included in the LICENSES directory
and also available at:

  * Apache-2.0: https://opensource.org/licenses/Apache-2.0
  * MIT: https://opensource.org/licenses/MIT
  * CC-BY-4.0: https://creativecommons.org/licenses/by/4.0/legalcode
