// Copyright 2024 The Khronos Group Inc.
// SPDX-License-Identifier: CC-BY-4.0

[[licenses]]
= Licenses and Contributor License Agreements

All content in a Khronos specification *must* be licensed.
This chapter covers:

  * <<licenses-choices, Choice of license>>
  * <<licenses-copyright, How to include a license in a file>>
  * How to document and verify repository licenses using
    <<licenses-reuse, REUSE>>
  * <<licenses-cla, Contributor License Agreements>>
  * <<licenses-artifacts, Licenses for ratified and non-ratified
    specification artifacts>>
  * When to use the <<licenses-confidential, Confidential Repository
    Notice>>

This chapter incorporates and supersedes the "`Khronos Open Source
Repository Resources`" document in the member Causeway area.


[[licenses-choices]]
== Choice of License

The Khronos default licenses for specifications are:

  * Specification source (such as asciidoc markup, or Markdown) and related
    documentation files are under the
    link:htps://creativecommons.org/licenses/by/4.0/[Creative Commons
    Attribution 4.0 License] to enable re-mixing.
  * Source code such as build scripts and example code is under the
    link:htps://www.apache.org/licenses/LICENSE-2.0[Apache 2.0 License].
  * When there is a compelling requirement for source code to be usable in a
    downstream LGPL project, the Working Group can approve a _dual license_
    on specific files, so that they can also be used under an
    LGPL-compatibile MIT License.
    Please consult with Neil Trevett before taking this step.
  * Published specification artifacts - generated files such as HTML and PDF
    documents - are placed under the Khronos Specification Copyright License
    so long as they are Ratified Specifications.
    This is required so that such specifications bring Khronos licensees
    under the umbrella of the Khronos IP agreements.
    Ths Khronos Specification Copyright License should never be used on
    markup or source files, or on specification artifacts that include
    non-ratified content, such as vendor extensions.

[NOTE]
.Note
====
In the past, we have used a variety of other licenses.
If your Working Group has a compelling reason to use a different, existing
open source license, please consult with Neil Trevett before taking this
step.

Please do not modify an existing open source license, or create a new one.
====


[[licenses-copyright]]
== Including a License and Copyright Statement in a File

Every Khronos-authored file *must* have an associated copyright statement,
including both the copyright (author and dates) and the <<spdx-id-table,
_SPDX License Identifier_>> of the license applying to that file.

In most cases, the copyright statement is included as a comment at the
earliest possible syntactically valid place in the file.

[NOTE]
.Note
====
In the past, we recommended including the complete license text in every
file.
When SPDX license identifiers and <<licenses-reuse, REUSE>> are used, only a
single copy of each license text need appear, in the `LICENSES` directory.
====

[NOTE]
.Note
====
In the asciidoc markup of the following examples, the pass:[{empty}]
attribute is included to avoid confusing <<licenses-reuse, REUSE>>.

The actual copyright statement should be included as shown in the rendered
output of this chapter, with the pass:[{empty}] attribute removed.
====

Examples using the default licenses are:

[source,c++,subs=attributes+]
.Makefile or Shell Script with Apache 2.0 License
----
# Copyright 2023-2024 The Khronos Group Inc.
# SPDX-License-{empty}Identifier: Apache-2.0

...
----

[source,asciidoc,subs=attributes+]
.Asciidoc Markup File with Creative Commons Attribution 4.0 License
----
// Copyright 2024 The Khronos Group Inc.
// SPDX-License-{empty}Identifier: CC-BY-4.0

...
----

[source,xml,subs=attributes+]
.XML Data File with Dual License
----
<?xml version="1.0" encoding="UTF-8"?>
<registry>
    <comment>
Copyright 2015-2024 The Khronos Group Inc.
SPDX-License-{empty}Identifier: Apache-2.0 OR MIT
    </comment>
...
----


[[licenses-implicit]]
=== Licenses for Unmodifiable or Externally Sourced Files

There are some cases where you may not be able to include an explicit
copyright statement in the format described above:

  . _Unmodifiable_ files need not have an explicit license statement
    included if their file format does not support it easily, or if the
    REUSE tool does not know how to extract the license from the file
    metadata.
    Examples include image and raw binary data files.
  . _Externally Sourced_ files come from other open source projects.
    One example is a script that is used in our build toolchain with slight
    modifications.
    Such files *must* have an open source license that is compatible with
    the Khronos licenses for the purposes they are required for.
    However, the way in which these licenses are specified may be different,
    such as including the complete license text in their copyright header,
    or implcitly using the LICENSE file of their source repository to apply
    to every file in that repository.
    Even if their license allows it, Khronos should never modify that
    license other than by adding Khronos as a copyright owner along with the
    original author, under the same license.

To provide a license for these files, add them to the `.reuse/dep5` file
described below for the <<licenses-reuse, REUSE>> tool.


[[licenses-documenting]]
== Documenting Licenses

The full and unmodified license text for each license used in the repository
*must* be included in the `LICENSES` directory.
Every license uses *must* have a corresponding SPDX license identifier.
The sample repository already includes the following licenses, which cover
most use cases:

[[spdx-id-table]]
.Licenses in the Sample Specification Repository
[options="header"]
|====
| SPDX License Identifier | Filename | Description
| `Apache-2.0`
    | `LICENSES/Apache-2.0.txt`
    | Apache 2.0
| `CC-BY-4.0`
    | `LICENSES/CC-BY-4.0.txt`
    | Creative Commons Attribution 4.0
| `LicenseRef-KhronosSpecCopyright`
    | `LICENSES/LicenseRef-KhronosSpecCopyright.adoc`
    | Khronos Specification Copyright License
| `MIT`
    | `LICENSES/MIT.txt`
    | MIT License
|====

If you need license text and SPDX license identifiers for other open source
licenses, obtain them from another Khronos repository already using those
licenses, or from the <<spdx-licenses, SPDX License List>> on the SPDX
website.

If you need to use a license not found on the SPDX website, please talk with
Jon Leech and Neil Trevett first.
This may happen if you are using a file from an open source project with a
nonstandard license, which is uncommon.
It may also happen if you are using a proprietary license *other* than the
Khronos Specification Copyright License, which is already included in this
repository.
Khronos should make every reasonable effort to avoid using such proprietary
licenses.


[[licenses-reuse]]
=== License Verification With REUSE

The <<reuse, REUSE>> tool is used in <<ci-reuse, Continuous Integration>> to
guarantee that all files in this repository are appropriately licensed.

REUSE verifies that every file in the repository has a license, and that
every license is included in the `LICENSES` directory.

Please make certain that you include the REUSE <<ci-jobs, `license-check` CI
job>> in any new repositories.


==== Adding Licenses to `dep5`

Files that do not and cannot have explicit license information included,
such as the <<licenses-implicit, Licenses for Unmodifiable or Externally
Sourced Files>> discussed above, *must* have their licenses documented in
the file `.reuse/dep5`.

Some examples of the `dep5` syntax for a file or group of files are:

[source]
----
Files: images/*.svg
Copyright: 2015-2024 The Khronos Group Inc.
License: CC-BY-4.0

Files: config/khronos.css
Copyright: 2013 Dan Allen
License: MIT
----

The `Files:` line contains the whitespace-separated names of one or more
files in the repository.
Wildcards are allowed.

The `Copyright` line contains the copyright statement for those files.
If there is already a copyright statement in the file without a
corresponding license, it should be copied verbatim.

The `License` line contains the SPDX license identifier of those files.

Multiple sections may be added to `dep5` for different licenses.
Be careful not to include filenames repeatedly, or include filenames which
already have explicit licenses.
When a filename is repeated in `dep5` with incompatible licenses, behavior
is unpredictable.

REUSE has other useful functionality, such as generating a license manifest,
that Working Groups may find useful.


[[licenses-cla]]
== Contributor License Agreements

Every contribution to Khronos repositories *must* be appropriately licensed
by its author.
This is ensured by _Contributor License Agreements_ and (for Khronos members
who make contributions) by the Khronos member agreements and IP policies.

All Khronos members are strongly encouraged to execute the
link:https://members.khronos.org/wg/General/document/928[Khronos Corporate
Open Source CLA] to cover their contributions made under the Apache 2.0
license.
Khronos members may edit their designated employees in Schedule A by
emailing mailto:memberservices@khronos.org[Member Services].

Additionally, CLAs are integrated into our GitHub repositories such that all
contributors *must* agree to the CLA before their pull requests can be
merged.
There are several possible CLAs that can be configured, depending on the
nature of the repository:

  * For most specification repositories, use the
    link:https://members.khronos.org/wg/General/document/939[Specification
    Mixed Repository CLA], which covers contributions under both CC-BY 4.0
    and Apache 2.0 licenses.
  * For repositories containing _only_ specification source documents under
    CC-BY 4.0 and _no_ Apache 2.0 materials, use the
    link:https://members.khronos.org/wg/General/document/932[Specification
    CLA].
  * For repositories containing _only_ source code under Apache 2.0 and _no_
    CC-BY 4.0 materials, use the
    link:https://members.khronos.org/wg/General/document/931[Khronos Apache
    2.0 CLA].
  * For repositories containing _only_ source code under the MIT license,
    use the link:https://members.khronos.org/wg/General/document/23998[MIT
    Click Through CLA].

[NOTE]
.Note
====
Repositories which start out using only one license are likely to eventually
include material under other licenses, so the Mixed Repository CLA is the
most forward-looking option.
Choose the repository CLA with this in mind.
====

To integrate a CLA with a new repository, contact our administrator,
mailto:webservices@khronosgroup.org[James Riordon].


[[licenses-artifacts]]
== Licenses for Ratified and Non-Ratified Specification Artifacts

When creating a specification, asciidoc (or other markup) files are
converted into HTML and/or PDF form more suitable for viewing in a web
browser.

These HTML or PDF files are referred to here as "`specification artifacts`"
or simply "`artifacts`".

[NOTE]
.Note
====
Historically we have published both HTML and PDF artifacts for our
specifications.
PDF artifacts can become very large and have limited use cases but more
readily support downloading for offline use, which some people appreciate.

Carefully consider which artifacts you wish to publish.
It is difficult to withdraw a particular specification format you have
published in the past, and easy not to publish that format in the first
place.
====

Specification artifacts can be submitted to the Khronos Board of Promoters
for ratification.
Artifacts, whether ratified or not, can be published in the Khronos Registry
for public consumption.

In either case, artifacts *must* be placed under a form of the
link:{specrepofiles}/config/copyright-spec.adoc[Khronos Specification
Copyright License].
By setting appropriate asciidoc attributes, this license can be used for
both *ratified* and *unratified* specifications.
See the comments in the license markup for details.
The Working Group and its Specification Editor are responsible
for ensuring that the appropriate license is used for artifacts they publish.

The Specification License is _not_ an open source license, even though the
markup files that went into creating artifacts are under such a license.
The purposes of the Specification Copyright include:

  * stating that the artifact was generated by Khronos
  * describing its ratification status with respect to the Khronos IP
    Policy
  * noting any trademarks that are used in the artifact.

[NOTE]
.Note
====
The link:{specrepofiles}/config/copyright-spec.adoc[Khronos Specification
Copyright License] found in the Sample-Docs repository is derived from the
link:https://members.khronos.org/wg/General/document/25728[Khronos Ratified
Specification Header] and
link:https://members.khronos.org/wg/General/document/23703[Khronos
Specification Copyright License Header] in the member Causeway area.

The Khronos Specification License has been reformatted for asciidoc markup,
and uses asciidoc conditionals to control inclusion of different parts of
the license as required.
Using it in an actual specification repository requires further editing to
include details and trademarks as appropriate for that repository, and to
select appropriate parts of the license.
====


=== Licenses for Other Published Artifacts

For a document which is not a specification requiring ratification or with
IP concerns, including the Sample Specification itself, you may use the
link:{specrepofiles}/config/copyright-ccby.adoc[CC-BY-4.0 license] on the
artifacts, as well as the input markup files.

[NOTE]
.Note
====
TODO Can we do away with the "`Khronos Document Copyright Licenses`"
entirely in favor of CC-BY?
====


[[licenses-confidential]]
== Confidential Repository Notice

The following notice *must* be placed in any repository covered by the
Khronos NDA:

[source,txt]
----
include::{config}/ConfidentialRepositoryNoticeApr18.txt[]
----

[NOTE]
.Note
====
The source of this Notice is in the
link:https://members.khronos.org/wg/General/document/938[member file area].
====
