// Copyright 2024 The Khronos Group Inc.
// SPDX-License-Identifier: CC-BY-4.0

// The asciidoc [glossary] template cannot contain subsections.

[appendix]
[[lexicon]]
= Lexicon

This appendix defines terms and abbreviations used in the
Specification.


[[glossary]]
== Glossary

The terms defined in this section are used consistently throughout the
Specification and may be used with or without capitalization, although
proper nouns such as "`Khronos`" should always be capitalized.

[[khronos-specification]]
Khronos Specification::
    A specification document authored and published by the Khronos Group,
    defining an API, language, or other standard.

[[sample-specification]]
Sample Specification::
    This document.
    A reference and guide to writing an actual <<khronos-specification,
    Khronos specification>>, but not itself a Khronos specification.

SPDX::
    The Software Package Data Exchange, which defines conventions and
    terminology used when applying licenses to this repository.


[[lexicon-common-abbreviations]]
== Common Abbreviations

The abbreviations and acronyms defined in this section are sometimes used in
the Specification and the API where they are considered clear and
commonplace.

License ID:
    A SPDX license identifier, used to refer to one of the licenses used in
    this repository.
